### ISSUE TITLE
Two issued with Karing no server available profile may be expired

### ISSUE THREAD

**Issue by crowlink** [KaringX/karing#101]
I have two serious problem usuing Karing.
1. After a while we got this error no server available profile may be expired. but  I have non-expired profile and I  have to delete profiles and add one by one again. it will happened more if you play with configs.
2.After a while ussing Karing Connection will be very slow or dead and after reset settings it will be O.K Soon.
Thanks

**Comment by GooRingX** [comment]
1. After reproducing, please back up the zip file backed up by the developer.
2. Troubleshooting

**Comment by GooRingX** [comment]
For question 1, there are two possible reasons for this:
1. All configurations are expired
2. All server delay detections failed, and [auto select]->Filter Invalid Servers is enabled. If no server is available, this error will be reported. The new version (>=284) has updated the prompt. If this problem is found again, please confirm whether it is case 2
For question 2, if it is Android, please update to version 285 to see if there is any improvement. If it is iOS, please go to settings- disable [Automatic Sleep]
