### ISSUE TITLE
Major Improvements for Auto Select

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [KaringX/karing#184]
**Dear Karing Development Team,**

I hope this message finds you well. As you know, users of the Karing client worldwide face severe filtering in their countries, leading to instability of certain protocols and servers. The Auto Select feature can be a lifesaver in these situations. Personally, I prefer using Clash Meta, Sing-box, and Hiddify over v2rayNG because I can benefit from a similar Auto Select feature in Karing, but in a more optimized manner. This prompted me to write this issue report to ensure the remarkable Karing client becomes even more comprehensive in this capability.

1. **Improving Config Selection in Auto Select:**
   The most critical improvement needed is refining and enhancing the selection of configurations based on ping. Although Karing's selections are usually appropriate, there are times when the client chooses a high-ping or even no-ping configuration. Implementing a mechanism similar to Clash, where pings are taken two or three times, and the best config is chosen based on the average ping, could be beneficial. Alternatively, evaluating and selecting configs based on long-term stability and speed or even randomly selecting from configs that are mostly valid could make Auto Select significantly more robust.

2. **Instant Config Change Upon Disconnection:**
   One major feature lacking in Auto Select is the instant switch to a new configuration upon disconnection, eliminating the need to wait for ping tests or manual user intervention. This would ensure users maintain a stable connection in most circumstances.
![IMG_4125](https://github.com/user-attachments/assets/9f00aa2e-34f8-4b67-b1e0-20d8dc4d9153)
   *Quote:* Similar functionality is implemented in the Shadowrocket app.

3. **Revisiting Default Settings of Auto Select:**
   I understand that many settings, such as the Latency Check Interval, are set high or disabled to conserve battery, but at what cost? An 8-hour interval is far too long, and I have not seen such a duration in any of the clients I've used. According to my research, most clients like Shadowrocket, Hiddify App, V2box, and Stash have this interval set to 10 minutes (600 seconds). Given the instability of certain configs and servers in heavily filtered countries like China, Russia, Iran, and others, this interval seems much more appropriate. Additionally, please enable "Re-check Latency when Network Changes" and "Update the current server after Manual Latency Check" by default.
![IMG_4129](https://github.com/user-attachments/assets/10c29149-4016-4c82-9f08-6a758a78fbd5)

I hope all three of the above points are addressed, and we see great changes for Auto Select in Karing soon. If other users have additional suggestions, they can comment below this issue to help improve Auto Select and assist the dedicated developers.

**Respectfully, Brooklyn.**

**Comment by GooRingX** [comment]
1. First of all, Karing does not use Ping, but Urltest. In addition, the latest version has improved the Urltest test, and the new test value is closer to the actual experience; As for the problem of using high-latency nodes, this statement is not accurate, because the data on the interface is delayed compared to the actual detection
2. Auto select itself is automatically switched, that is, after the node fails, it will switch to the next fastest node. I don’t know if this is the function you are talking about?
3. Regarding the feedback about the delay detection interval being too long, there is basically no user feedback, and no changes will be made for the time being; Regarding the problem that these functions you mentioned are not turned on by default, some devices may frequently trigger network changes, resulting in frequent delay detection. In addition, most network changes have no effect on the proxy server, so there is no need to turn it on by default. The other one is enabled by default

**Comment by BOR-LAND** [comment]
> GooRingX

What is missing is the ability to use Auto Select within a specific subscription. For example, I would like to use a specific subscription with proxy servers in Germany (DE Auto Select) only for a specific route, e.g. google.com.

Or need the ability to exclude certain subscriptions or proxies from Auto Select.
