### ISSUE TITLE
Adding Ping Test Icon to the Main Screen

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [KaringX/karing#190]
**Dear Karing Development Team,**

I hope this message finds you well.

Given that Karing is a client that pays attention to every detail, I believe it is essential to add a ping test icon to the main screen of the app. This would eliminate the need to open the configuration menu each time and allow users to test ping for all configurations with a single click on the main screen.
![IMG_4164](https://github.com/user-attachments/assets/f3a389ff-d651-42b1-923d-f92847d16ce5)
_*Quote:* The icon could be placed next to the 🔄 icon, or a new ping test could be initiated when clicking on the ping display._

Additionally, when clicking the 🔄 icon on the main screen to refresh the subscription link's data usage and time, it would be very helpful if the subscription link update is also applied simultaneously. This change would greatly assist novice users.

Thank you for your consideration.

**Best regards, Amirhossein Brooklyn.**

**Comment by GooRingX** [comment]
1. It is not very meaningful to test all delays with one button on the main screen, because you cannot see the delay data feedback, and it may cause the operation to take a long time.
2. The cost of directly updating the subscription configuration is too high. Generally speaking, just set the automatic update time in the corresponding subscription.
