### ISSUE TITLE
TUN connection error (Win 10)

### ISSUE THREAD

**Issue by Warelax** [KaringX/karing#224]
This message appears when connecting in TUN mode (Windows 10). When reconnecting, everything is fine. When reconnecting after changing settings, rules, etc., it appears again. The System proxy is disabled. Running with admin permissions. Versions karing_1.0.27.346_windows_x64.exe and earlier.

![Karing](https://github.com/user-attachments/assets/65f6a16f-3722-4f71-92e0-7c53911da83d)

**Comment by Pedro-e** [comment]
I can confirm that this is a very annoying problem in Windows 10 that I have experienced in the latest versions even version 325 and the only temporary way to solve the problem is to wait 14 seconds and get the error and reconnect until this problem is temporarily fixed, disconnecting and manually connecting or manually selecting the server will not fix the problem.   And turning Mux-tls-tun-dns on and off won't solve the problem.

Thanks to the esteemed developers and professional Karing app

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27.349
